### ISSUE TITLE
Bug: Windows 32-bit binary is not being compiled properly in tests

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-evtx#11]
crossのwindows 32ビットビルドはそもそも失敗して、fallbackで自動てきにデフォルトの64ビットをビルドしているようです。
32ビットビルドのチェックができていないようです。

<img width="990" alt="cant cross compile windows 32 binary with cross" src="https://user-images.githubusercontent.com/71482215/194787288-b959095e-95bc-4f4e-9eb1-592b3430097f.png">

**Comment by YamatoSecurity** [comment]
64-bitも同じようにdocker imageエラーが出ています:
[cross] warning: `cross` does not provide a Docker image for target x86_64-pc-windows-msvc, specify a custom image in `Cross.toml`.

**Comment by hitenkoku** [comment]
ありがとうございます。確認してみます。
