### ISSUE TITLE
Bug: quick-xml 0.24+ doesn't compile on windows 32 bit

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-evtx#12]
quick-xml 0.24+はWindows 32 bitではコンパイルできません。
コマンド: rustup run stable-i686-pc-windows-msvc cargo build --release

エラーはこんな感じです: (rust evtx crateもビルドに失敗します）
![IMG_3311](https://user-images.githubusercontent.com/71482215/194787504-02c5e073-3c52-4af5-9e71-22b645eaab59.jpg)
![IMG_3310](https://user-images.githubusercontent.com/71482215/194787506-878de5e7-df70-49ea-8b6e-594f32f326bd.jpg)

@hitenkoku 
このエラーはこちらで直せるんですか？それともquick-xmlの問題ですか？

**Comment by hitenkoku** [comment]
こちらの環境(Windows11)で以下手順で行ったときに特にエラーなく
hayabusa-evtxがコンパイルできることを確認しました(cargo.tomlでquick-xmlは0.25.*であることを確認済みです)
もう少し確認します。

```
> rustup install stable-i686-pc-windows-msvc
> rustup run stable-i686-pc-windows-msvc cargo build --release --target=i686-pc-windows-msvc
```

**Comment by hitenkoku** [comment]
提示しているエラーはquick-xmlで発生しているエラーなのでこちらで修正することは出来ないです。

**Comment by YamatoSecurity** [comment]
なるほど。。私の環境が悪いかもしれないので、Windows 11でやってみます。

**Comment by hitenkoku** [comment]
すみませんがよろしくお願いいたします。

**Comment by YamatoSecurity** [comment]
大変失礼しました。`rustup install stable-i686-pc-windows-msvc`を実行したら、クロスコンパイラーが更新され、無事にコンパイルできました。
