### ISSUE TITLE
Improve speed test by using Mimalloc 

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-evtx#14]
https://github.com/Yamato-Security/hayabusa/pull/777#issue-1419666787 にもある通りメモリアロケータをMimallocに変えることで処理速度が向上したのでhayabusa-evtxにも導入する

**Comment by fukusuket** [comment]
@YamatoSecurity @hitenkoku 

I got the benchmark on [the branch](https://github.com/Yamato-Security/hayabusa-evtx/commit/34a6b1356ac3296c957c0323d3eba8d8761f0d3b) and results is as follows. :) 

before
Elapsed time: 00:00:17.178
Elapsed time: 00:00:17.776
Elapsed time: 00:00:17.528

after
Elapsed time: 00:00:17.100
Elapsed time: 00:00:17.457
Elapsed time: 00:00:17.626

Setting mimalloc in evtx crate doesn't seem to affect performance🤔

According to the following comments in forum, You can't set multi global allocator in one binary :(
https://users.rust-lang.org/t/how-to-make-multi-global-allocator-in-one-binary-or-dylib/36643

I also checked the implementation evtx ...🔍
The global allocator was only set in [evtx_dump.rs(RpMalloc, Jmelloc)](https://github.com/omerbenamram/evtx/blob/v0.8.0/src/bin/evtx_dump.rs#L19-L28), Therefore I think the mimalloc setting affects performance only when the [evtx_dump command directly executed](https://github.com/omerbenamram/evtx#evtx_dump-binary-utility).

**Comment by hitenkoku** [comment]
@fukusuket Thanks for your research. Your reserach is very helpful.

@YamatoSecurity  hayabusa performace do not improved through adding mimalloc in evtx  crate by this research. So I want to close this issue.
