### ISSUE TITLE
Adapt CDATA in evtx (compile error in quick-xml >=0.24)

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-evtx#6]
## Expected 
- quick-xml 0.24以降を導入してコンパイルが成功できるようにすること

> Windows 32ビットバイナリをコンパイルしてみたら、quick-xml 0.24.0+のバージョンでは失敗しています。
> rust evtx crateもquick-xmlが0.23.0でないとコンパイルに失敗します。
> 0.24.0+のバージョンではCDATAのバグを直しているっぽいけど、rust evtx crateではCDATAに対応していないので、今は最新版を使わなくても良さそうです。また、そもそもevtxでCDATAが実際にに使われていないようです。

https://github.com/Yamato-Security/hayabusa/pull/701#issue-1375517708

**Comment by YamatoSecurity** [comment]
@hitenkoku evtx作者がquick-xml 0.24に対応したようです。https://github.com/omerbenamram/evtx/commit/d08934e267c235f48c34e59b299e45e1061e56ad

こちらにも反映できますか？
